import {test,expect} from 'bun:test';
import {buildMatchReport} from '../src/lib/matchReport';
test('report retains JD and actual component arithmetic without duplicate components',()=>{
 const components=[{key:'requiredSkill',label:'Required skills',points:23,maxPoints:30,reason:'Four of six requirements supported'},{key:'responsibilitySemantic',label:'Responsibilities',points:7,maxPoints:25,reason:'Limited responsibility coverage'},{key:'roleTitle',label:'Role',points:15,maxPoints:15,reason:'Demonstrated'},{key:'seniority',label:'Seniority',points:8,maxPoints:15,reason:'Entry transition'},{key:'location',label:'Location',points:3,maxPoints:5,reason:'Partial'},{key:'domainEducation',label:'Education',points:0,maxPoints:10,reason:'Unverified'}];
 const text=buildMatchReport({jobs:[{title:'Engineer',fitScore:56,source:'example',description:'FULL RETAINED JOB DESCRIPTION',descriptionQuality:'full',matchedSkills:['React','React','Next.js'],provenance:[{source:'example',externalId:'public-id'}],breakdown:components.map(c=>({label:c.key,value:c.points})),scoreDetails:{components,seniorityPenalty:0,scoreCap:null},availability:{status:'unknown',reason:'Challenge blocked verification'}}],run:{versions:{rankerVersion:'test'},queries:['Full Stack Developer'],timings:{retrievalMs:10}},scope:'loaded',total:20});
 expect(text).toContain('components 56');expect(text).toContain('final 56');expect(text).toContain('loaded filtered 1 of 20');expect(text).toContain('FULL RETAINED JOB DESCRIPTION');expect(text).toContain('Provenance:');expect(text).toContain('test');expect(text).not.toContain('React, React');expect(text.match(/Score component:/g)).toHaveLength(6);
});
test('penalty and cap are explicit; unknown scores and evidence are not invented',()=>{
 const text=buildMatchReport({jobs:[{title:'Senior Engineer',fitScore:20,scoreDetails:{components:[{key:'a',label:'Score',points:80,maxPoints:100,reason:'Returned evidence'}],seniorityPenalty:50,scoreCap:20,scoreCapReasons:['Seniority gap']}},{title:'Missing score',salary:{min:0},missingSkills:['HTML','HTML']}]});
 expect(text).toContain('components 80 - penalty 50, capped at 20; final 20');expect(text).toContain('unknown (not returned)');expect(text).toContain('Requirements not evidenced in resume: HTML');expect(text).toContain('omitted qualifications cannot be verified');expect(text).not.toContain('[object Object]');
});
